#!/usr/bin/env python3
"""
build_schema.py — Combine all modular SQL files into a single schema.sql

Usage:
    python db/build_schema.py                    # Copy to clipboard
    python db/build_schema.py --write            # Write to db/schema.sql
    python db/build_schema.py --print            # Print to stdout
    python db/build_schema.py --validate         # Validate only (no output)
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List


class SchemaBuilder:
    def __init__(self, db_root: Path):
        self.db_root = db_root
        self.sections = [
            ("Core Tables", [
                "core/01_cleaned_reviews.sql",
                "core/02_scrape_runs.sql",
            ]),
            ("Extraction Tables", [
                "extraction/01_entities_raw.sql",
                "extraction/02_relations_raw.sql",
                "extraction/03_sentiments_raw.sql",
                "extraction/04_extraction_checkpoint.sql",
            ]),
            ("Canonical Tables", [
                "canonical/01_normalization_runs.sql",
                "canonical/02_entities.sql",
                "canonical/03_entity_aliases.sql",
                "canonical/04_entity_alias_candidates.sql",
                "canonical/05_entity_mentions.sql",
                "canonical/06_relations.sql",
                "canonical/07_relation_mentions.sql",
                "canonical/08_sentiments.sql",
                "canonical/09_sentiment_mentions.sql",
                "canonical/10_normalization_checkpoints.sql",
            ]),
            ("Functions", [
                "functions/01_get_unprocessed_reviews.sql",
                "functions/02_update_checkpoint.sql",
                "functions/03_refresh_canonical_aggregates.sql",
            ]),
            ("Indexes", [
                "indexes/core_indexes.sql",
                "indexes/extraction_indexes.sql",
                "indexes/canonical_indexes.sql",
            ]),
        ]

    def read_sql_file(self, rel_path: str) -> str:
        """Read a single SQL file."""
        full_path = self.db_root / rel_path
        if not full_path.exists():
            raise FileNotFoundError(f"Missing SQL file: {full_path}")
        return self.make_non_destructive(full_path.read_text(encoding="utf-8"))

    def make_non_destructive(self, sql: str) -> str:
        """Remove destructive DDL and make create statements idempotent."""
        lines = []
        for line in sql.splitlines():
            if re.match(r"^\s*DROP\s+(TABLE|FUNCTION|INDEX|VIEW)\s+IF\s+EXISTS\b", line, re.IGNORECASE):
                continue
            lines.append(line)

        output = "\n".join(lines)
        output = re.sub(
            r"\bCREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS\b)",
            "CREATE TABLE IF NOT EXISTS ",
            output,
            flags=re.IGNORECASE,
        )
        output = re.sub(
            r"\bCREATE\s+UNIQUE\s+INDEX\s+(?!IF\s+NOT\s+EXISTS\b)",
            "CREATE UNIQUE INDEX IF NOT EXISTS ",
            output,
            flags=re.IGNORECASE,
        )
        output = re.sub(
            r"\bCREATE\s+INDEX\s+(?!IF\s+NOT\s+EXISTS\b)",
            "CREATE INDEX IF NOT EXISTS ",
            output,
            flags=re.IGNORECASE,
        )
        return output

    def build(self) -> str:
        """Build the complete schema by concatenating all sections."""
        parts = []

        # Header
        parts.append("-- " + "=" * 70)
        parts.append("-- Trip_Advisor Heritage Intelligence Platform — Complete Database Schema")
        parts.append("-- " + "=" * 70)
        parts.append("-- Generated by db/build_schema.py")
        parts.append("-- DO NOT EDIT THIS FILE DIRECTLY — Edit modular files in db/ instead")
        parts.append("-- " + "=" * 70)
        parts.append("")

        # Build each section
        for section_name, files in self.sections:
            parts.append("-- " + "═" * 70)
            parts.append(f"-- {section_name.upper()}")
            parts.append("-- " + "═" * 70)
            parts.append("")

            for file_path in files:
                try:
                    content = self.read_sql_file(file_path)
                    parts.append(f"-- >>> {file_path}")
                    parts.append(content.strip())
                    parts.append("")
                except FileNotFoundError as e:
                    raise FileNotFoundError(f"Required file missing: {file_path}") from e

        # Footer
        parts.append("-- " + "=" * 70)
        parts.append("-- END OF SCHEMA")
        parts.append("-- " + "=" * 70)

        return "\n".join(parts)

    def validate(self) -> List[str]:
        """Validate all files exist without building."""
        missing = []
        for _, files in self.sections:
            for file_path in files:
                full_path = self.db_root / file_path
                if not full_path.exists():
                    missing.append(file_path)
        return missing


def copy_to_clipboard(text: str) -> bool:
    """Copy text to system clipboard."""
    try:
        import pyperclip
        pyperclip.copy(text)
        return True
    except ImportError:
        return False
    except Exception:
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Build unified schema.sql from modular SQL files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument("--write", action="store_true",
                        help="Write output to db/schema.sql")
    parser.add_argument("--print", action="store_true",
                        help="Print schema to stdout")
    parser.add_argument("--validate", action="store_true",
                        help="Validate all files exist without output")
    parser.add_argument("--clipboard", action="store_true",
                        help="Copy to clipboard (default if no flags)")

    args = parser.parse_args()

    # Default behavior: copy to clipboard if no explicit flags
    if not any([args.write, args.print, args.validate]):
        args.clipboard = True

    db_root = Path(__file__).parent
    builder = SchemaBuilder(db_root)

    # Validate first
    missing = builder.validate()
    if missing:
        print("✗ Validation failed - missing files:", file=sys.stderr)
        for f in missing:
            print(f"  - {f}", file=sys.stderr)
        return 1

    if args.validate:
        print(f"✓ All {sum(len(f) for _, f in builder.sections)} schema files present")
        return 0

    # Build schema
    try:
        schema = builder.build()
    except FileNotFoundError as e:
        print(f"✗ Error: {e}", file=sys.stderr)
        return 1

    # Output handling
    if args.write:
        output_path = db_root / "schema.sql"
        output_path.write_text(schema, encoding="utf-8")
        print(f"✓ Schema written to {output_path}")
        print(f"  Size: {len(schema):,} characters")

    if args.print:
        print(schema)

    if args.clipboard:
        if copy_to_clipboard(schema):
            print("✓ Schema copied to clipboard (ready to paste in Supabase SQL Editor)")
        else:
            print("⚠ Could not copy to clipboard (pyperclip not installed or unavailable)")
            print("  Install with: pip install pyperclip")
            print("  Or use --write to save to file instead")

    return 0


if __name__ == "__main__":
    sys.exit(main())
