"""
Generic Nepal heritage token configuration for automatic alias learning.

This module must not contain named entity mappings. It only defines reusable
lexical classes and generic transliteration equivalents that help the matcher
compare labels across heritage reviews.
"""

DESCRIPTOR_TOKENS = {
    "ancient",
    "architectural",
    "artistic",
    "authentic",
    "beautiful",
    "big",
    "ceremonial",
    "central",
    "classic",
    "crowded",
    "cultural",
    "daily",
    "deeply",
    "deep",
    "devotional",
    "divine",
    "evening",
    "famous",
    "foreigners",
    "foreign",
    "golden",
    "great",
    "historic",
    "historical",
    "holy",
    "important",
    "inner",
    "large",
    "local",
    "main",
    "major",
    "medieval",
    "morning",
    "nearby",
    "old",
    "ornate",
    "outer",
    "peaceful",
    "public",
    "religious",
    "royal",
    "sacred",
    "small",
    "spiritual",
    "stone",
    "traditional",
    "wooden",
}

HERITAGE_STYLE_TOKENS = {
    "buddhist",
    "hindu",
    "indigenous",
    "newar",
    "newari",
    "shaivite",
    "tantric",
    "vajrayana",
    "vedic",
}

ARCHITECTURE_TOKENS = {
    "arch",
    "architecture",
    "bahal",
    "bahi",
    "balcony",
    "bell",
    "bells",
    "bihar",
    "carving",
    "carvings",
    "chaitya",
    "chhen",
    "chok",
    "chowk",
    "courtyard",
    "courtyards",
    "dabali",
    "degal",
    "deval",
    "door",
    "doorway",
    "durbar",
    "dyochhen",
    "gate",
    "gates",
    "golden",
    "gumba",
    "hiti",
    "house",
    "mandap",
    "mandapa",
    "mandir",
    "monastery",
    "monument",
    "monuments",
    "mural",
    "murals",
    "pagoda",
    "pagodas",
    "palace",
    "pati",
    "pond",
    "pokhari",
    "resthouse",
    "roof",
    "roofs",
    "sattal",
    "shikhara",
    "shrine",
    "shrines",
    "sikhara",
    "spout",
    "spouts",
    "stupa",
    "stupas",
    "temple",
    "temples",
    "toran",
    "torana",
    "tundal",
    "tundals",
    "tower",
    "towers",
    "vihara",
    "window",
    "windows",
}

SACRED_SPACE_TOKENS = {
    "bank",
    "banks",
    "burning",
    "cave",
    "caves",
    "complex",
    "cremation",
    "ground",
    "grounds",
    "ghat",
    "ghats",
    "gorge",
    "guthi",
    "kund",
    "kunda",
    "math",
    "monastery",
    "museum",
    "nunnery",
    "platform",
    "premises",
    "river",
    "riverbank",
    "riverfront",
    "site",
    "space",
    "spring",
    "square",
    "tank",
}

RITUAL_TOKENS = {
    "abhishek",
    "abhisheka",
    "aarti",
    "aarati",
    "arati",
    "arti",
    "bhajan",
    "chant",
    "chanting",
    "circumambulation",
    "cremation",
    "darshan",
    "deepdan",
    "funeral",
    "havan",
    "hom",
    "homa",
    "jatra",
    "kora",
    "offering",
    "offerings",
    "parikrama",
    "pooja",
    "pradakshina",
    "prayer",
    "prayers",
    "puja",
    "ritual",
    "rituals",
    "tarpan",
    "worship",
}

RELIGIOUS_ROLE_TOKENS = {
    "bhakta",
    "devotee",
    "devotees",
    "guru",
    "lama",
    "lamas",
    "monk",
    "monks",
    "nun",
    "nuns",
    "pandit",
    "pilgrim",
    "pilgrims",
    "priest",
    "priests",
    "pujari",
    "pujaris",
    "sadhu",
    "sadhus",
    "yogi",
    "yogis",
}

SACRED_OBJECT_TOKENS = {
    "butter",
    "diya",
    "flag",
    "flags",
    "flower",
    "flowers",
    "garland",
    "garlands",
    "incense",
    "lamp",
    "lamps",
    "linga",
    "lingam",
    "mask",
    "masks",
    "offering",
    "offerings",
    "prasad",
    "prayer",
    "rudraksha",
    "statue",
    "statues",
    "thangka",
    "thangkas",
    "toran",
    "trident",
}

MATERIAL_TOKENS = {
    "brick",
    "bronze",
    "copper",
    "gilded",
    "gold",
    "golden",
    "metal",
    "stone",
    "terracotta",
    "wood",
    "wooden",
}

ENTITY_TYPE_TOKENS = {
    "actor",
    "area",
    "ceremonies",
    "ceremony",
    "courtyard",
    "event",
    "festival",
    "gate",
    "ghat",
    "ghats",
    "ground",
    "hall",
    "monument",
    "object",
    "pagoda",
    "place",
    "prayer",
    "river",
    "ritual",
    "room",
    "shrine",
    "space",
    "spot",
    "stupa",
    "temple",
    "tower",
} | ARCHITECTURE_TOKENS | SACRED_SPACE_TOKENS | RITUAL_TOKENS | RELIGIOUS_ROLE_TOKENS | SACRED_OBJECT_TOKENS

TOKEN_EQUIVALENTS = {
    "aarati": "aarti",
    "arati": "aarti",
    "arti": "aarti",
    "abhisheka": "abhishek",
    "ceremonies": "ceremony",
    "chok": "chowk",
    "courtyards": "courtyard",
    "dyochhen": "house",
    "deval": "temple",
    "dhara": "spout",
    "gates": "gate",
    "ghats": "ghat",
    "gumba": "monastery",
    "hiti": "spout",
    "hom": "havan",
    "homa": "havan",
    "kund": "kunda",
    "lamas": "lama",
    "linga": "lingam",
    "mandir": "temple",
    "sikhara": "shikhara",
    "monks": "monk",
    "monuments": "monument",
    "murals": "mural",
    "nuns": "nun",
    "pagodas": "pagoda",
    "palaces": "palace",
    "parikrama": "pradakshina",
    "pilgrims": "pilgrim",
    "pooja": "puja",
    "prayers": "prayer",
    "priests": "priest",
    "pujaris": "pujari",
    "rituals": "ritual",
    "roofs": "roof",
    "sadhus": "sadhu",
    "shrines": "shrine",
    "spouts": "spout",
    "statues": "statue",
    "stupas": "stupa",
    "temples": "temple",
    "thangkas": "thangka",
    "tundals": "tundal",
    "towers": "tower",
    "windows": "window",
    "yogis": "yogi",
}

ALIAS_EXTRA_TOKENS = (
    DESCRIPTOR_TOKENS
    | HERITAGE_STYLE_TOKENS
    | ENTITY_TYPE_TOKENS
    | MATERIAL_TOKENS
)
